"""empty message

Revision ID: c9805ac8f4b2
Revises: 77f71677f7b9
Create Date: 2022-11-04 22:30:02.794451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9805ac8f4b2'
down_revision = '77f71677f7b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_fav')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_fav',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='character_fav_character_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='character_fav_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='character_fav_pkey')
    )
    # ### end Alembic commands ###
